# Generated by Django 2.2.1 on 2019-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='last_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='last_payment_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
