# Generated by Django 2.2.1 on 2019-08-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190820_1500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentmodel',
            table='payment',
        ),
    ]
